### ISSUE TITLE
Issues in the submitted 1.0.0 packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/opengl-meta#2]
While reviewing the submitted 1.0.0 packages I've noticed the following issues:

1. The project name in `manifest` is `opengl-meta` instead of `libopengl-meta`. Unless there is a good reason to deviate, we make it the same as the git project/repository name.

2. The `opengl-meta-examples` feels inconsistent with the `libopengl-meta` name. I realize this is a choice between two "consistencies": (1) call it `libopengl-meta-examples` because it is an examples package for `libopengl-meta` or (2) call it `opengl-meta-examples` because it is not a library. I am personally leaning towards preferring (1) since it's highly unlikely there will ever be a real library called `libopengl-meta-examples`. What do you think?

3. I believe `libopengl-meta/buildfile` is missing:

```
# Don't install tests.
#
tests/: install = false
```

4. The `libopengl-meta/libopengl-meta/buildfile` should list all the libraries as prerequisites of the default target (`./`). I believe this is the reason why most `test-installed` steps fail: none except the first library mentioned are installed:

```
./: lib{opengl-gl opengl-glu ...}
```

5. In `tests/*/buildfile` there are stray `testscript{**}`.

6. `opengl-meta-examples/buildfile` needs fixing per https://github.com/build2/HOWTO/blob/master/entries/keep-build-graph-config-independent.md (didn't you get a warning during publishing?)

7. `opengl-meta-examples` is just an ordinary package that depends on `libopengl-meta` and is built seperately. Instead you may want to list it as `examples: opengl-meta-examples == $` in `libopengl-meta`, for details see https://github.com/build2/HOWTO/blob/master/entries/handle-tests-with-extra-dependencies.md

I am going to hold off on publishing this package until we finilize at least the more important of these (1, 2, 4).

**Comment by Rookfighter** [comment]
Rregarding your points:

1. I would simply prefer to rename the repo to `opengl-meta`. This should then also solve the inconsistency mentioned in 2.

3.-7. I will fix that.

Edit:
Regarding 6. I can't remember for sure, but usually I check outputs for warnings or errors.

**Comment by boris-kolpackov** [comment]
> I would simply prefer to rename the repo to `opengl-meta`.

In the end it's up to you, but see my comment in the `libvulkan-meta` issue.

> This should then also solve the inconsistency mentioned in 2.

For me the inconsistency is between the library package name (`libopengl-meta`) and the examples package name for this library (`opengl-meta-examples`), not between the repository name and the examples package name. Once the packages are published, nobody sees the repository name.

> Regarding 6. I can't remember for sure, but usually I check outputs for warnings or errors.

Yes, I just realized, the way you did (via a variables), you wouldn't get a warning.

**Comment by Rookfighter** [comment]
> For me the inconsistency is between the library package name (libopengl-meta) and the examples package name for this library (opengl-meta-examples), not between the repository name and the examples package name. Once the packages are published, nobody sees the repository name.

Alright, got your point here. Just for my understanding, why is the `imgui-examples` package treated differently then? You made me rename it from `libimgui-examples` to just `imgui-examples` here: https://github.com/build2-packaging/imgui/pull/2#issuecomment-1154033834 
What's the particular difference?

**Comment by boris-kolpackov** [comment]
> You made me rename it from `libimgui-examples` to just `imgui-examples`.

Gosh, I did, didn't I? Wonder what was I thinking... I think I only considered the "examples are not a library" side of it but didn't think of the "would be good to have examples for a library start with the exact library name" side. Perhaps the fact that there are multiple `libimgui*` libraries obscured this somewhat for me. But now I think it should have been called `libimgui-examples`. Sorry about that.

**Comment by Rookfighter** [comment]
Haha, don't worry, let's just pretend you wanted to teach me a lesson :D
I will fix the packages accordingly.

**Comment by boris-kolpackov** [comment]
Thanks! In many ways we are still figuring details like these out and as you encounter new real-world use-case, you often get new perspectives.

**Comment by boris-kolpackov** [comment]
AFAICS, all of this has been fixed, thanks!
